### ISSUE TITLE
Support setting rust flags in Xargo.toml

### ISSUE THREAD

**Issue by RalfJung** [japaric/xargo#142]
It would be nice to be able to set rust compiler flags in Xargo.toml. For example, when using xargo to build a libstd for miri (following <https://github.com/solson/miri/pull/171>), particular flags need to be set. Right now, we need to tell people to set these themselves; if we could pit them into Xargo.toml, that would make things much nicer.

Or would Cargo.toml be the better place for this?

**Comment by japaric** [comment]
At the end Xargo ends up calling Cargo to do all the hard work. And there's already a method to customize rust compiler flags when using Cargo and that's the RUSTFLAGS env variable and the `target.$T.rustflags` setting in `.cargo/config`. I don't intent to add a rustflags setting to Xargo.toml since that's something that is already well supported by Cargo.

Also Xargo.toml is for Xargo / sysroot specific features. Adding rustflags there would mean "use these rustflags *only* for the sysroot build" which would be a footgun IMO as using different rustflags when compiling the sysroot vs when compiling the top crate can lead to linker errors (e.g. different float ABI) and/or runtime errors (e.g. wrong codegen options).

**Comment by RalfJung** [comment]
I see.  So I may ask for cargo to gain such a flag in Cargo.toml then, and then Xargo would (automatically?) also use that.

**Comment by japaric** [comment]
Yes, Xargo uses project local settings, like profile.dev, specified in Cargo.toml.

Not automatically; there's a whitelist (not configurable; it's hardcoded). The sysroot has its own Cargo.toml so only a few settings make to pass along from the target Cargo project Cargo.toml to the sysroot's.

**Comment by RalfJung** [comment]
Actually adding this to Cargo.toml is not easy, I can see why they did not do that... after all, the flags should be the same for the entire compilation, so this is not really a per-crate thing. Hm.
