### ISSUE TITLE
README out of date

### ISSUE THREAD

**Issue by SpaceManiac** [japaric/xargo#150]
The README currently says:

>To build std without the "jemalloc" feature, apply the patch in rust-lang/rust#37975.

This is no longer accurate; the patch is not necessary. Since https://github.com/rust-lang/rust/commit/70d2372adaf48bb24f8b829417229149bd103e4a, `std = { features = ["force_alloc_system"] }` is sufficient to disable jemalloc.

**Comment by RalfJung** [comment]
The README has been updated by <https://github.com/japaric/xargo/pull/157>.

Notice that, according to <https://github.com/rust-lang/rust/issues/43637#issuecomment-320226134>, `force_alloc_system` is *not* supposed to be used like this. What this flag means is that every program compiled with this libstd can only use the system allocator. If your program tries to set its own allocator, compilation will fail because now two allocators are set (one by libstd, one by your program).

**Comment by Others** [comment]
I actually think `force_alloc_system` doesn't even do anything. See this (rust-lang/rust/issues/43637#issuecomment-320228953) comment:

> ah sorry, since jemalloc broke I've said this in a lot of places so I've forgotten who it's been said to. Apart from anything else though, it's actually a no-op right now because it was removed in the global allocator PR - my patch would make it actually do something again.

**Comment by RalfJung** [comment]
Yes, but that patch has landed since then. So right now, it does do something.

**Comment by Others** [comment]
@RalfJung Yeah, good point. Really the README should just suggest the correct settings in `my-custom-target.json`. That's the correct way to do it.
