### ISSUE TITLE
Replace $HOME/.xargo with $XDG_DATA_HOME/xargo

### ISSUE THREAD

**Issue by linkmauve** [japaric/xargo#46]
In order to respect the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html), like cargo before it, xargo should switch to the standard `$XDG_DATA_HOME/xargo` directory (by default `$HOME/.local/share/xargo` when `$XDG_DATA_HOME` isn’t set).

**Comment by japaric** [comment]
Cargo uses HOME not XDG_HOME_DIR AFAICT so I'd prefer not to differ from Cargo on this matter.

**Comment by linkmauve** [comment]
They use `$XDG_DATA_HOME/cargo` currently, which is already better than yet another dotfile, and are [in](https://github.com/rust-lang/cargo/issues/1734) [the](https://github.com/rust-lang/cargo/pull/2127) [process](https://github.com/rust-lang/rfcs/pull/1615) of moving their cache and configuration to the proper `$XDG_CACHE_HOME/cargo` and `$XDG_CONFIG_HOME/cargo` directories, respectively.

**Comment by japaric** [comment]
> They use $XDG_DATA_HOME/cargo currently

@linkmauve I grepped for xdg in Cargo repository and there's only one match in a test, which actually unsets the env var.

My installation also uses ~/.cargo and there's @SShrike confirmation.

The "in the process" links you mention point to a RFC which hasn't been accepted.

I'd be happy to move Xargo to XDG *after* Cargo does it but I won't if Cargo doesn't.

I'm going to close this because it's not actionable until Cargo makes the change. Feel free to open a new issue by the time Cargo moves to XDG!

**Comment by jakbyte** [comment]
Cargo supports setting the `CARGO_HOME` environment variable, though, so there should be a `XARGO_HOME` environment variable.

**Comment by RalfJung** [comment]
> so there should be a XARGO_HOME environment variable.

@jakbyte is anything wrong with `XARGO_HOME`? I've been using it for years.

**Comment by wackbyte** [comment]
it took me a year to see this, but it does seem to work :slightly_smiling_face:
