### ISSUE TITLE
Allow sending target to `cargo install`

### ISSUE THREAD

**Issue by jackpot51** [japaric/xargo#80]
Currently, if `xargo install --target some_target --root some_root` is used, it will say:
`Unknown flag: '--target'`

**Comment by japaric** [comment]
Ah, well. That's because Cargo itself doesn't support passing `--target` to its `install` subcommand. You'll have to request that feature in Cargo and once that's implemented the corresponding Xargo command will Just Work (modulo bugs of course).

In general, Xargo doesn't provide any command that Cargo doesn't and that's because, at the end, Xargo just calls Cargo with the same arguments it (Xargo) was called with.

**Comment by jackpot51** [comment]
Ok, that makes sense
