### ISSUE TITLE
Getting the following Error while installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by slayerjain** [japaric/xargo#87]
parallels@ubuntu:~$ cargo install xargo
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading xargo v0.2.1
error: An unknown error occurred

To learn more, run the command again with --verbose.

**Comment by japaric** [comment]
This is an upstream issue.

https://crates.io ssl certificate has expired and all downloads that Cargo tries to do from it will error in the same way. The Rust team is already aware of the problem and it's working to fix it right now.

I'm going to close this since this is not a Xargo specific issue that will solve itself in due time but thanks for the report!
